# Generated by Django 4.1.3 on 2022-11-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_of_price',
            field=models.CharField(choices=[('сум', 'Uz'), ('у.е', 'En')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
