# Generated by Django 4.1.3 on 2022-11-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_type_of_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data',
            new_name='specifications',
        ),
    ]
